### ISSUE TITLE
Błędy kompilacji

### ISSUE THREAD

**Issue by rafikus** [MruV-RP/mruv-pb-web#5]
Nie mogę włączyć projektu reacta ze względu na błędy w paczce, już naprawiłem importy w middleware. Zostały błędy bezpośrednio w paczce.
```
./node_modules/mruv-pb-web/server/ServerServiceClientPb.ts 24:9
Module parse failed: Unexpected token (24:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| export class MruVServerServiceClient {
>   client_: grpcWeb.AbstractClientBase;
|   hostname_: string;
|   credentials_: null | { [index: string]: string; };
```

Możliwe że do tego muszę dodać loader, ale jeżeli to w paczce jest to wydaje mi się że loader powinien być w paczce.

**Comment by rafikus** [comment]
Poza tym są też błędy typów
```
TypeScript error in C:/Users/Rafał/WebstormProjects/mruv-new/client/react/node_modules/mruv-pb-web/accounts/AccountsServiceClientPb.ts(63,7):
Argument of type 'MethodInfo<RegisterAccountRequest, RegisterAccountResponse>' is not assignable to parameter of type 'MethodDescriptor<RegisterAccountRequest, RegisterAccountResponse>'.
  Property 'createRequest' is missing in type 'MethodInfo<RegisterAccountRequest, RegisterAccountResponse>' but required in type 'MethodDescriptor<RegisterAccountRequest, RegisterAccountResponse>'.  TS2345

    61 |       request,
    62 |       metadata || {},
  > 63 |       this.methodInfoRegisterAccount,
       |       ^
    64 |       callback);
    65 |   }
    66 | 
```

**Comment by Mrucznik** [comment]
Z tego co pamiętam szukałem już rozwiązania by naprawić ten błąd i chyba było to związane z gRPC i wersją kompilatora protoc, sprawdzę czy dam radę to naprawić zaktualizowaniem kompilatora do najnowszej wersji.

**Comment by Mrucznik** [comment]
Masz jakiś najprostszy sposób by zreprodukować ten błąd?

**Comment by rafikus** [comment]
@Mrucznik npm start na mruv-react, drugi błąd po zakomentowaniu Characters.js

**Comment by Mrucznik** [comment]
Spróbuję zreprodukować ten błąd w https://github.com/MruV-RP/mruv-web-example bo i tak przydałoby się napisać jakiś przykład dla grpc-web.
BTW. Super by było pyknąć generator testów dla każdej paczki ale nie wiem, na ile jest to możliwe i pracochłonne.

**Comment by Mrucznik** [comment]
Ten commit https://github.com/MruV-RP/mruv-protos/commit/546e9c40db383f0702c2785e43f422f60ac72ef5 i https://github.com/MruV-RP/mruv-pb-web/commit/da1b6de3fb7c66c6530565f577504859ce11eea1 powinien naprawić błąd.

**Comment by rafikus** [comment]
No niestety
```
TypeScript error in C:/Users/Rafał/WebstormProjects/mruv-new/client/react/node_modules/mruv-pb-web/accounts/AccountsServiceClientPb.ts(63,7):
Argument of type 'MethodInfo<RegisterAccountRequest, RegisterAccountResponse>' is not assignable to parameter of type 'MethodDescriptor<RegisterAccountRequest, RegisterAccountResponse>'.
  Property 'createRequest' is missing in type 'MethodInfo<RegisterAccountRequest, RegisterAccountResponse>' but required in type 'MethodDescriptor<RegisterAccountRequest, RegisterAccountResponse>'.  TS2345

    61 |       request,
    62 |       metadata || {},
  > 63 |       this.methodInfoRegisterAccount,
       |       ^
    64 |       callback);
    65 |   }
    66 | 
```

**Comment by Mrucznik** [comment]
A na pewno masz najnowsze mruv-pb-web z mastera? Bo budowanie tsc w projekcie już działa.

**Comment by rafikus** [comment]
@Mrucznik Tak, Najpierw zrobiłem po prostu `npm i` później `npm update`, a na koniec wywaliłem całe node_modules i zrobiłem ponownie `npm i`
Możesz samemu sprawdzić

**Comment by Mrucznik** [comment]
Naprawione - paczka po stronie klienta się nie zupdateowała poprawnie przez te bugilagi z niezmienianiem versji w package.json przy generowaniu plikow pb.
Zamykam :)
